articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'

urlpatterns = [
    path('my_articles/', views.ArticlesList, name='my-articles'),
    path('detail/<int:pk>', views.ArticleDetail, name='detail'),
    path('create/', views.ArticleCreate, name='create-article'),
    path('update/<int:pk>/', views.ArticleUpdate,name='update'),
    path('delete/<int:pk>', views.ArticleDelete, name='delete'),


        
]

comments/urls.py
from django.urls import path
from .views import CommentDelete, CommentEdit
from . import views

app_name = 'comments'

urlpatterns = [
    # Chemin pour supprimer un commentaire
    path('delete/<int:pk>/', CommentDelete.as_view(), name='delete'),
    path('edit/<int:pk>/', CommentEdit.as_view(), name='edit'),
    path('post/<int:pk>/', views.post_a_comment, name='post-comment')
]

main/urls.py
from django.urls import path, include
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from main import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('my_auth.urls')),
    path('', include('main.urls')),
    path('accounts/', include('profiles.urls')),
    path('articles/', include('articles.urls')),
    path('comments/', include('comments.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

comments/models.py
from django.db import models
from my_auth.models import CustomUser
from articles.models import Article
# Create your models here.

class Comment(models.Model):
    user: CustomUser = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    article: Article = models.ForeignKey(Article, on_delete=models.CASCADE)
    text: str = models.TextField()
    create_date = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return f'comment from {self.user} to {self.article}'

comments/forms.py
from django import forms
from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']

comments/views.py
from django.shortcuts import render, redirect
from .models import Comment
from .forms import CommentForm
from django.http import JsonResponse
from django.views.generic import  DeleteView, UpdateView
from django.urls import reverse_lazy
from django.shortcuts import get_object_or_404
from articles.models import Article
# Create your views here.



 # je fais une classView pour editer un commentaire:
class CommentDelete(DeleteView):
    model = Comment
    template_name = 'comments/delete_comment.html'

    def get_success_url(self):
        return reverse_lazy('articles:detail', kwargs={'pk': self.object.article.pk})
    

class CommentEdit(UpdateView):
    model = Comment
    template_name = 'comments/edit_comment.html'
    fields = ['text']

    def get_success_url(self):
        return reverse_lazy('articles:detail', kwargs={'pk': self.object.article.pk})
    
def post_a_comment(request, pk):
    article = get_object_or_404(Article, pk=pk)
    if request.method == 'POST':
        print('ca passe ici')
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.user = request.user
            comment.article = article
            comment.save()
    return redirect(request.META.get('HTTP_REFERER', 'articles:index'))  

comments/templates/comments/_comment.html
<!--  Ici je met le plan d'un commentaire model : -->



        <small>
            From : <strong>{{comment.user.username}}</strong> 
        </small>

        <p>
            {{comment.text}}
        </p>

        <small>
            posted : {{comment.create_date|date:"d M Y H:i"}}
        </small><br>


        <!-- gestion suppression et edit pour l'user du message,
            et delete only pour l'user de l'article -->
        {% if comment.user == request.user %}
        <small>
            <a href="{% url 'comments:edit' comment.pk %}">edit</a> //
            <a href="{% url 'comments:delete' comment.pk %}">delete</a>
        </small>
        {% elif article.user == request.user %}
        <small>
            <a href="{% url 'comments:delete' comment.pk %}">delete</a>
        </small>
        {% endif %} <br>

     

comments/templates/comments/_post_a_comment.html
        <!-- commentaire à poster : -->
        <div class="commentary-form-container">
            <h5>Leave comment:</h5>
            <form action="{% url 'comments:post-comment' article.id %}" method="POST">
                {% csrf_token %}
                {{form.as_p}}
                <input type="submit" value="Post!">
            </form>
        </div>

comments/templates/comments/delete_comment.html
{% extends 'base.html' %}


        {% block title %} 
            Delete Comment
        {% endblock title %}




        {% block content %}
        <h3>Are your sure to delete:</h3>
        <p>
            {{object.text}}
        </p>

        <form action="" method="POST">
            {% csrf_token %}
            <input type="submit" value="DELETE" name="" id="">
        </form>
        <a href="{% url 'articles:detail' object.article.pk %}">Cancel</a>

        {% endblock content %}

comments/templates/comments/edit_comment.html
{% extends 'base.html' %}


        {% block title %} 
            Edit Comment
        {% endblock title %}




        {% block content %}
        <h3>Edit your comment:</h3>

        <form action="" method="POST">
            {% csrf_token %}
            {{form.as_p}}
            <button type="submit">Update com!</button>
        </form>
        <br>
        <a href="{% url 'articles:detail' object.article.pk %}">Cancel</a>

        {% endblock content %}