articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'

urlpatterns = [
    path('my_articles/', views.ArticlesList, name='my-articles'),
    path('detail/<int:pk>', views.ArticleDetail, name='detail'),
    path('create/', views.ArticleCreate, name='create-article'),
    path('update/<int:pk>/', views.ArticleUpdate,name='update'),
    path('delete/<int:pk>', views.ArticleDelete, name='delete'),


        
]

comments/urls.py
from django.urls import path
from .views import CommentDelete, CommentEdit
from . import views

app_name = 'comments'

urlpatterns = [
    # Chemin pour supprimer un commentaire
    path('delete/<int:pk>/', CommentDelete.as_view(), name='delete'),
    path('edit/<int:pk>/', CommentEdit.as_view(), name='edit'),
    path('post/<int:pk>/', views.post_a_comment, name='post-comment')
]

main/urls.py
from django.urls import path, include
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from main import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('my_auth.urls')),
    path('', include('main.urls')),
    path('accounts/', include('profiles.urls')),
    path('articles/', include('articles.urls')),
    path('comments/', include('comments.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

articles/models.py
from django.db import models
from my_auth.models import CustomUser
# Create your models here.

class Article(models.Model):
    user: CustomUser = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    title: str = models.CharField(max_length=200)
    image = models.ImageField(upload_to='photo_articles/', blank=True, null=True)
    text: str = models.CharField(max_length=2000, blank=True, null=True)
    create_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)

    def like_count(self) -> int:
        # donne le nombre total de like de l'article:
        return LikeArticle.objects.filter(article=self, liked=True).count()
    
    def user_like(self, user: CustomUser) -> bool:
        # donne la value du like pour un user donné:
        # first() donne la premiere value sinon None : si le like n'existe pas envoie none:
        like_instance = LikeArticle.objects.filter(article=self, user=user).first()
        return like_instance.liked if like_instance else False


    def __str__(self) -> str:
        return self.title
    

class LikeArticle(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    liked = models.BooleanField(default=False)

    # je créé une class pour que un user ne puisse faire l'action que une fois par article:
    class Meta:
        unique_together = ('user', 'article')

    def __str__(self) -> str:
        return f'Like for {self.article} from {self.user}'

    

comments/models.py
from django.db import models
from my_auth.models import CustomUser
from articles.models import Article
# Create your models here.

class Comment(models.Model):
    user: CustomUser = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    article: Article = models.ForeignKey(Article, on_delete=models.CASCADE)
    text: str = models.TextField()
    create_date = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return f'comment from {self.user} to {self.article}'

articles/forms.py
from django import forms
from django.forms import ModelForm
from .models import Article


class ArticleForm(ModelForm):
    class Meta:
        model = Article
        fields = ['title', 'image','text']

articles/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, HttpRequest
from .models import Article, LikeArticle
from .forms import ArticleForm
from django.contrib import messages
from comments.forms import CommentForm
from comments.models import Comment
from my_auth.models import CustomUser
from typing import Dict, List

# Create your views here.


def ArticlesList(request: HttpRequest) -> HttpResponse:
    articles: Article = Article.objects.filter(user=request.user).order_by('-create_date')  # Trier par date descendante
    form = CommentForm()
    ctx: dict[str, Article] = {'articles':articles, 'form':form}
    return render(request, 'articles/articles_list.html', ctx)
    



def ArticleCreate(request: HttpRequest) -> HttpResponse:
    if request.method == 'POST':
        form = ArticleForm(request.POST, request.FILES)
        if form.is_valid():
            new_article = form.save(commit=False)
            new_article.user = request.user
            new_article.save()
            return redirect('articles:my-articles')
    else:
        form = ArticleForm()
    ctx: Dict[str, ArticleForm] ={'form':form}
    return render(request, 'articles/create_article.html', ctx)





def ArticleUpdate(request: HttpRequest,pk:int) -> HttpResponse:
    article: Article = get_object_or_404(Article,pk=pk )
    if request.user != article.user:
        return redirect('articles:my-articles')
    if request.method == 'POST':
        form = ArticleForm(request.POST, request.FILES, instance=article)
        if form.is_valid():
             form.save()
             return redirect('articles:my-articles')

    else:
        form = ArticleForm(instance=article)
    ctx: Dict[str, ArticleForm] = {'form':form}
    return render(request, 'articles/update_article.html', ctx)






def ArticleDelete(request: HttpRequest, pk: int) -> HttpResponse:
    article: Article = get_object_or_404(Article, pk=pk)
    if request.method == 'POST':
        if request.POST.get('delete'):
            article.delete()
            messages.warning(request, f'You deleted the article : {article.title}.')
            return redirect('articles:my-articles')
        else:
            messages.info(request, 'You canceled the delete of your article !')
            return redirect('articles:my-articles')

    ctx: Dict[str, Article] = {'article':article}
    return render(request, 'articles/delete_article.html', ctx)



def ArticleDetail(request: HttpRequest, pk: int) -> HttpResponse:
    article: Article = get_object_or_404(Article, pk=pk)
    
    # je check si un object like existe deja, sinon ca envoie None (.first()),
    # puis je vais chercher le statut du like si il existe:
    user_like_statut: LikeArticle = LikeArticle.objects.filter(user=request.user, article=article).first()


    form: CommentForm = CommentForm()
    # recuperation des commentaires de l'article:
    comments: List[Comment] = article.comment_set.all()

    ctx: Dict[str, Article | List[Comment] | CommentForm | LikeArticle] = {
        'article':article,
        'comments':comments,
        'form':form,
        'user_like_statut':user_like_statut,
        
        }
    
    return render(request, 'articles/article_detail.html', ctx)

          








    

articles/templates/articles/_article.html
<!-- Ici je met la structure de mon article entier pour ne pas avoir a le refaire a chaque fois: -->

{% if article %}
<a href="{% url 'articles:detail' article.id %}"><h3>{{article.title}}</h3></a>

            {% if article.image %}
            <img src="{{article.image.url}}" alt="Article pic !">
            {% else %}
            <small>//No image for this post !//</small>
            {% endif %}
            <p>{{article.text}}</p>
            <small>
                Autor : <strong>{{article.user.username}} </strong> <br>
                Updated : {{article.update_date|date:"d M Y H:i"}}
            </small>

            
            <!-- if pour edit ou delete l'article si c'est le connecté le proprio -->
            {% if article.user == request.user %}
            <a href="{% url 'articles:update' article.id %}">Edit</a> ||
            <a href="{% url 'articles:delete' article.id %}">Delete</a>
            {% endif %}

{% else %}
            <h3>No article in database!</h3>

{% endif %}

articles/templates/articles/_full_article.html
<!-- corps de l'article a afficher : -->
<div class="article-detail-container">
    {% include 'articles/_article.html' %}
</div>


<!--  FAIT-->
<!--  affichage du coeur en fonction du dtatut du like: -->
<div class="like-container">
    {% include 'articles/_like.html' %}
</div>



<!--  FAIT -->
<!-- commentaire posté et visibles : -->
<div class="commentary-posted-container">
{% if article.comment_set.all %} 

    ################COMMENTS######## <br>

        {% for comment in article.comment_set.all %}
            {% include 'comments/_comment.html' %}
            <br>
            ----------------------------------------
            <br>
           
        {% endfor %}

    ########    ######   ####

{% else %}

<h4>No comment for now !</h4>

    {% endif %}
</div>

<!-- commentaire à poster : -->
    {% include 'comments/_post_a_comment.html' %}

articles/templates/articles/article_detail.html
{% extends 'base.html' %}


        {% block title %} 
            Details
        {% endblock title %}



        {% block content %}
        <h3>Article Details:</h3>
        <hr>

        <!--  FAIT -->
        <!-- corps de l'article a afficher : -->
        <div class="article-detail-container">
            {% include 'articles/_article.html' %}
        </div>


        <!--  FAIT-->
        <!--  affichage du coeur en fonction du dtatut du like: -->
        <div class="like-container">
            {% include 'articles/_like.html' %}
        </div>



        <!--  FAIT -->
        <!-- commentaire posté et visibles : -->
        <div class="commentary-posted-container">
        {% if comments %} 

            ################COMMENTS######## <br>

                {% for comment in comments %}
                    {% include 'comments/_comment.html' %}
                    <br>
                    ----------------------------------------
                    <br>
                   
                {% endfor %}

            ########    ######   ####

        {% else %}

        <h4>No comment for now !</h4>

            {% endif %}
        </div>

        <!-- commentaire à poster : -->
            {% include 'comments/_post_a_comment.html' %}

        {% endblock content %}

articles/templates/articles/articles_list.html
{% extends 'base.html' %}


        {% block title %} 
        My Posts
        {% endblock title %}




        {% block content %}

        <h3>Here my posts : updates</h3>

        <!-- Je boucle pour parcourir tout mes articles -->
        {% if articles %}

            {% for article in articles %}
               {% include 'articles/_full_article.html' %}
            {% endfor %}
        {% endif %}
        {% endblock content %}

articles/templates/articles/create_article.html
{% extends 'base.html' %}


        {% block title %} 
            Write post!
        {% endblock title %}




        {% block content %}

        <h3>Write your Post !!</h3>
        <div class="form-article-container">
            <form action="" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{form.as_p}}
                <input type="submit" value="Post!">

            </form>
        </div>
        {% endblock content %}

articles/templates/articles/delete_article.html
{% extends 'base.html' %}


        {% block title %} 
            Delete Post!
        {% endblock title %}




        {% block content %}
        <h3>Are you sure to delete the article:</h3>
        <ul>
            <li>Title : {{article.title}}</li>
            <li>Updated : {{article.update_date}}</li>
            
        </ul>

        <div class="form-article-delete-container">
            <form action="" method="POST">
                {% csrf_token %}
                <input type="submit" value="DELETE" name="delete" id="">
                <input type="submit" value="Back" name="back">
            </form>
        </div>


        {% endblock content %}

articles/templates/articles/old_article_detail.html
{% extends 'base.html' %}


        {% block title %} 
            Details
        {% endblock title %}




        {% block content %}
        <h3>Article Details:</h3>
        <hr>

        <!--  FAIT -->
<!-- corps de l'article a afficher : -->
        <div class="article-detail-container">
            <h3>{{article}}</h3>
            {% if article.image %}
            <img src="{{article.image.url}}" alt="Article pic !">
            {% else %}
            <small>No image for this post !</small>
            {% endif %}
            <p>{{article.text}}</p>
            <small>
                By {{article.user}} <br>
                {{article.update_date}}
            </small>





            <!--  FAIT-->
            <!--  affichage du coeur en fonction du dtatut du like: -->
            <div class="like-container">
                <form action="{% url 'articles:detail' article.id %}" method="POST">
                    {% csrf_token %}
                          <button type="submit" name="like" class="like-button" data-article-id="{{article.id}}">
                                {% if user_like_statut and user_like_statut.liked %}
                                    <span class="heart-liked">❤️</span>
                                {% else %}
                                    <span class="heart-avoid">🤍</span>
                                {% endif %}
                          </button>
                </form>

            </div>








            <!--  FAIT -->
            <!-- if pour edit ou delete l'article si c'est le connecté le proprio  -->
             {% if article.user == request.user %}
                <a href="{% url 'articles:update' article.id %}">Edit</a> ||
                <a href="{% url 'articles:delete' article.id %}">Delete</a>
             {% endif %}
            <hr>
        </div>



        <!--  FAIT -->
        <!-- commentaire posté et visibles : -->
        <div class="commentary-posted-container">
            {% if comments %} 
            ################COMMENTS######## <br>
                {% for comment in comments %}
                   <small>
                        from : {{comment.user}} 
                   </small>
                    <p>
                        {{comment.text}}
                    </p>
                    <small>
                        posted : {{comment.create_date}}
                    </small><br>
                            <!-- gestion suppression et edit pour l'user du message,
                              et delete only pour l'user de l'article -->
                            {% if comment.user == request.user %}
                            <small>
                                <a href="{% url 'comments:edit' comment.pk %}">edit</a> //
                                <a href="{% url 'comments:delete' comment.pk %}">delete</a>
                            </small>
                            {% elif article.user == request.user %}
                            <small>
                                <a href="{% url 'comments:delete' comment.pk %}">delete</a>
                            </small>
                            {% endif %} <br>
                    ################################### <br>
                {% endfor %}
            {% endif %}

        </div>

        <!-- commentaire à poster : -->
        <div class="commentary-form-container">
            <h5>Leave comment:</h5>
            <form action="" method="POST">
                {% csrf_token %}
                {{form.as_p}}
                <input type="submit" value="Post!">
            </form>
        </div>

        {% endblock content %}

articles/templates/articles/old_articles_list.html
{% extends 'base.html' %}


        {% block title %} 
        My Posts
        {% endblock title %}




        {% block content %}
        <h3>Here my posts :</h3>
        <!-- Je boucle pour parcourir tout mes articles -->
        {% if articles %}
            {% for article in articles %}
                <div class="article-container">
                    <h3>{{article.title}}</h3>
                    {% if article.image %}
                    <img src="{{article.image.url}}" alt="" >
                    {% else %}
                    <p>No picture for now 😊</p>
                    {% endif %}
                    <p>
                        {{article.text}}
                    </p>
                    <small>
                        for {{article.update_date|date:"F d, Y"}}
                    </small><br>
                    <small>
                        <a href="{% url 'articles:update' article.id %}">Edit</a> ||
                        <a href="{% url 'articles:delete' article.id %}">Delete</a>
                    </small>
                    <!--  affichage du coeur en fonction du dtatut du like: -->
            <div class="like-container">
                <form action="{% url 'articles:detail' article.id %}" method="POST">
                    {% csrf_token %}
                          <button type="submit" name="like" class="like-button" data-article-id="{{article.id}}">
                                {% if user_like_statut and user_like_statut.liked %}
                                    <span class="heart-liked">❤️</span>
                                {% else %}
                                    <span class="heart-avoid">🤍</span>
                                {% endif %}
                          </button>
                </form>

            </div>
                </div>
                <hr>
            {% endfor %}
        {% else %}
        <h4>Nothing for now !</h4>
        {% endif %}

        {% endblock content %}

articles/templates/articles/update_article.html
{% extends 'base.html' %}


        {% block title %} 
            Update post!
        {% endblock title %}




        {% block content %}

        <h3>Update your Post !!</h3>
        <div class="form-article-container">
            <form action="" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{form.as_p}}
                <input type="submit" value="Repost!">

            </form>
        </div>
        {% endblock content %}