articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'

urlpatterns = [
    path('my_articles/', views.ArticlesList, name='my-articles'),
    path('detail/<int:pk>', views.ArticleDetail, name='detail'),
    path('create/', views.ArticleCreate, name='create-article'),
    path('update/<int:pk>/', views.ArticleUpdate,name='update'),
    path('delete/<int:pk>', views.ArticleDelete, name='delete'),


        
]

main/urls.py
from django.urls import path, include
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
]

my_auth/urls.py
from django.urls import path, include
from . import views

app_name = 'my_auth'

urlpatterns = [
    path('registration/', views.registration, name='registration'),
    path('logout/', views.logout_view, name='logout'),
    path('login/', views.login_view, name='login')
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from main import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('my_auth.urls')),
    path('', include('main.urls')),
    path('accounts/', include('profiles.urls')),
    path('articles/', include('articles.urls')),
    path('comments/', include('comments.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

profiles/urls.py
from django.urls import path, include
from . import views

app_name = 'profiles'

urlpatterns = [
        path('creation/', views.ProfileCreate, name='create-profile'),
        path('my_profile/', views.ProfileShow, name='my-profile'),
        path('edit/', views.ProfileEdit, name='edit-profil'),
        path('doublon/', views.ProfilDoublon, name='doublon'),
        path('delete/', views.ProfileDelete, name='delete-profile')
        
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} {% endblock title %}</title>
</head>
<body>
    <a href="{% url 'main:home' %}"><h1>InstaKilo</h1></a>
   
    <hr>

    <!-- ma navbar en 3 parties:
            -connexion
            -profile
            -articles      
    -->
    <nav>
        <!-- Trucs pour la page profile etc -->
        <div class="profiles-links-container">
            <ul>               
                <a href="{% url 'profiles:my-profile' %}">My Profile</a>____
                <a href="{% url 'profiles:edit-profil' %}">Edit Profil</a>____
                <a href="{% url 'profiles:create-profile' %}">Create Profile</a>____
            </ul>
        </div>
        <!--  Trucs pour creer un compte -->
        <div class="accounts-links-container">
            <ul>
                 <a href="{% url 'my_auth:registration' %}">Create account</a>____

            </ul>
        </div>
        <!-- Trucs pour les articles  -->
         <div class="articles-links-container">
            <ul>
                <a href="{% url 'articles:my-articles' %}">My Articles</a>
                <a href="{% url 'articles:create-article' %}">Create New Article</a>
            </ul>
         </div>


         <!-- salutation et statut de l'user -->
        <div class="messages-container">
                <p>
                    {% if user.is_authenticated %}
                    Hello {{user.username}} ! <a href="{% url 'my_auth:logout' %}">logout</a>
                    {% else %}
                    tu n'es pas connecté ! <a href="{% url 'my_auth:login' %}">login</a>  or <a href="{% url 'my_auth:registration' %}">registration!</a>
                    {% endif %} 
                </p>
        </div>
        <!-- message de renseignement des actions precedentes genre delte/update de trucs -->
        <div class="explication-message-container">
            {% if messages %}
            <hr>
                {% for message in messages %}
                <p>
                    {{message}}
                </p>
                {% endfor %}
            {% endif %}

        </div>
    </nav>

    <hr>
    
        {% block content %}
        {% endblock content %}
</body>
</html>