articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'

urlpatterns = [
    path('my_articles/', views.ArticlesList, name='my-articles'),
    path('detail/<int:pk>', views.ArticleDetail, name='detail'),
    path('create/', views.ArticleCreate, name='create-article'),
    path('update/<int:pk>/', views.ArticleUpdate,name='update'),
    path('delete/<int:pk>', views.ArticleDelete, name='delete'),


        
]

main/urls.py
from django.urls import path, include
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from main import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('my_auth.urls')),
    path('', include('main.urls')),
    path('accounts/', include('profiles.urls')),
    path('articles/', include('articles.urls')),
    path('comments/', include('comments.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

comments/models.py
from django.db import models
from my_auth.models import CustomUser
from articles.models import Article
# Create your models here.

class Comment(models.Model):
    user: CustomUser = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    article: Article = models.ForeignKey(Article, on_delete=models.CASCADE)
    text: str = models.TextField()
    create_date = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return f'comment from {self.user} to {self.article}'

main/models.py
from django.db import models

# Create your models here.

main/views.py
from django.shortcuts import render
from articles.models import Article
from django.http import HttpRequest, HttpResponse
from typing import Dict
from comments.forms import CommentForm
# Create your views here.

def home(request: HttpRequest) -> HttpResponse:
    articles: Article = Article.objects.all()
    form = CommentForm()
    ctx: Dict[str, Article] = {'articles':articles, 'form':form}
    return render(request, 'main/home.html', ctx)

main/templates/main/home.html
{% extends 'base.html' %}

        {% block title %} 
        Feed
        {% endblock title %}

        {% block content %}
        <h3>Feed of Insta: TAMER</h3>

        <!-- Je boucle pour parcourir tout mes articles -->
{% if articles %}


    {% for article in articles %}

                        <!-- corps de l'article a afficher : -->
        <div class="article-detail-container">
            {% include 'articles/_article.html' %}
        </div>


        <!--  FAIT-->
        <!--  affichage du coeur en fonction du dtatut du like: -->
        <div class="like-container">
            {% include 'articles/_like.html' %}
        </div>




        <!--  TODO : mettre  un lien rapide pour acceder au detail pour voir tout les coms / rendre joli. -->
        <!-- commentaire posté et visibles : -->
        <div class="commentary-posted-container">
        {% if article.comment_set.last %} 

            ################LAST COMMENT######## <br>
                {% with article.comment_set.last as comment %}
                    {% include 'comments/_comment.html' %}
                    <br>
                    ----------------------------------------
                    <br>
                {% endwith %}

            ########    ######   ####

        {% else %}
        <h4>No comment for now !</h4>

        {% endif %}
        </div>

        <!-- commentaire à poster : -->
            {% include 'comments/_post_a_comment.html' %}
      
    {% endfor %}



{% else %}

        <h4>Nothing for now !</h4>
        
{% endif %}

        {% endblock content %}

main/templates/main/old_home.html
{% extends 'base.html' %}

{% block title %} HomePage {% endblock title %}
                     


{% block content %}


<!-- Feed d'actualité : -->
 <hr>
 <h2>Feed of Posts here :</h2>
{% if articles %}

    {% for article in articles %}
        <div class="article-feed-container">
            <a href="{% url 'articles:detail' article.id %}">
                <h3>{{article}}</h3>
            </a>
            
            {% if article.image %}
            <img src="{{article.image.url}}" alt="Article pic !">
            {% else %}
            <small>No image for this post !</small>
            {% endif %}
            <p>{{article.text}}</p>
            <small>
                By {{article.user}} <br>
                {{article.update_date}}
            </small>
            <!-- if pour edit ou delete l'article si c'est le connecté le proprio -->
             {% if article.user == request.user %}
                <a href="{% url 'articles:update' article.id %}">Edit</a> ||
                <a href="{% url 'articles:delete' article.id %}">Delete</a>
             {% endif %}
            
            <!--  affichage du coeur en fonction du dtatut du like: -->
            <div class="like-container">
                <form action="{% url 'articles:detail' article.id %}" method="POST">
                    {% csrf_token %}
                          <button type="submit" name="like" class="like-button" data-article-id="{{article.id}}">
                                {% if user_like_statut and user_like_statut.liked %}
                                    <span class="heart-liked">❤️</span>
                                {% else %}
                                    <span class="heart-avoid">🤍</span>
                                {% endif %}
                          </button>
                </form>

            </div>
            <hr>
        </div>

    {% endfor %}

{% endif %}


{% endblock content %}